Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like: a) Addition of 2 in all the element b) Multiply 3 with all the elements c) Divide every element by 2



In [1]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])

# a) Addition
added_array = array + 2
print("Array after adding 2:", added_array)

# b) Multiply
multiplied_array = array * 3
print("Array after multiplying by 3:", multiplied_array)

# c) Divide every element by 2
divided_array = array / 2
print("Array after dividing by 2:", divided_array)


Array after adding 2: [3 4 5 6 7]
Array after multiplying by 3: [ 3  6  9 12 15]
Array after dividing by 2: [0.5 1.  1.5 2.  2.5]


Questions on Basic NumPy Array: a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) b) Find the most frequent value and their indice(s) in the following arrays: i. x = np.array([1,2,3,4,5,1,2,1,1,1]) ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])



In [2]:
import numpy as np

# Given array
arr = np.array([1, 2, 3, 6, 4, 5])

# Reverse the array
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)

#for x
x = np.array([1,2,3,4,5,1,2,1,1,1])

# Find the most frequent value
unique, counts = np.unique(x, return_counts=True)
most_frequent_value = unique[np.argmax(counts)]

# Find indices of the most frequent value
indices = np.where(x == most_frequent_value)[0]

print("Most frequent value in x:", most_frequent_value)
print("Indices:", indices)

# for y
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

# Find the most frequent value
unique, counts = np.unique(y, return_counts=True)
most_frequent_value = unique[np.argmax(counts)]

# Find indices of the most frequent value
indices = np.where(y == most_frequent_value)[0]

print("Most frequent value in y:", most_frequent_value)
print("Indices:", indices)


Reversed array: [5 4 6 3 2 1]
Most frequent value in x: 1
Indices: [0 5 7 8 9]
Most frequent value in y: 1
Indices: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows: a) Access 1st row, 2nd column b) Access 3rd row, 1st column



In [3]:
import numpy as np

arr = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

element_a = arr[0, 1]
print("Element at 1st row, 2nd column:", element_a)

element_b = arr[2, 0]
print("Element at 3rd row, 1st column:", element_b)


Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


Q.4 Write program to create an 1-D NumPy array named <> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

In [4]:
import numpy as np

rujul= np.linspace(10, 100, 25)

print("Dimensions of the array:", rujul.ndim)
print("Shape of the array:", rujul.shape)
print("Total elements in the array:", rujul.size)
print("Data type of each element:", rujul.dtype)
print("Total number of bytes consumed by the array:", rujul.nbytes)

transposed_array_reshape = rujul.reshape(25, 1)
print("Transposed array using reshape():\n", transposed_array_reshape)

transposed_array_T = rujul.T
print("Transposed array using T attribute:\n", transposed_array_T)

Dimensions of the array: 1
Shape of the array: (25,)
Total elements in the array: 25
Data type of each element: float64
Total number of bytes consumed by the array: 200
Transposed array using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transposed array using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<your_name>>.

In [5]:
import numpy as np

rujul = np.array([[10, 20, 30, 40],
                  [50, 60, 70, 80],
                  [90, 15, 20, 35]])

mean_value = np.mean(rujul)
median_value = np.median(rujul)
max_value = np.max(rujul)
min_value = np.min(rujul)
unique_elements = np.unique(rujul)

print("Mean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique elements:", unique_elements)

reshaped_rujul = rujul.reshape(4, 3)
print("Reshaped array (4 rows, 3 columns):\n", reshaped_rujul)

resized_rujul = np.resize(rujul, (2, 3))
print("Resized array (2 rows, 3 columns):\n", resized_rujul)


Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array (4 rows, 3 columns):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array (2 rows, 3 columns):
 [[10 20 30]
 [40 50 60]]
